plugin:
    name: 'acornassociated.backendlocalization::lang.plugin.name'
    description: 'acornassociated.backendlocalization::lang.plugin.description'
    author: acornassociated
    icon: oc-icon-adjust
    homepage: ''
